// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package workflow

type Event struct {
	RunID   string `json:"run_id"`
	Version int32  `json:"version"`
	Data    []byte `json:"data"`
}

type Run struct {
	ID      string `json:"id"`
	Version int32  `json:"version"`
}

type Script struct {
	Hash string `json:"hash"`
	Data []byte `json:"data"`
}
